# Generated by Django 3.1.7 on 2021-04-20 18:51

import datetime
from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(decimal_places=1, default=Decimal('5.0'), max_digits=2)),
                ('name', models.TextField(default='')),
                ('address', models.TextField(blank=True, default='', null=True)),
                ('qr_url', models.TextField(blank=True, default='', null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=14, max_digits=16, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=14, max_digits=16, null=True)),
                ('all_bonuses', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='clubs_avatars')),
                ('count_people', models.IntegerField(default=0)),
                ('contacts', models.TextField(blank=True, default='', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MyImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='club_images')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='')),
                ('image', models.ImageField(blank=True, null=True, upload_to='services_categories')),
            ],
        ),
        migrations.CreateModel(
            name='TimeLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(default=datetime.datetime(1900, 1, 1, 0, 0))),
                ('end_time', models.TimeField(default=datetime.datetime(1900, 1, 1, 0, 1))),
                ('price', models.IntegerField(default=0)),
                ('company_id', models.IntegerField(blank=True, null=True)),
                ('day', models.CharField(blank=True, choices=[('0', 'Понедельник'), ('1', 'Вторник'), ('2', 'Среда'), ('3', 'Четверг'), ('4', 'Пятница'), ('5', 'Суббота'), ('6', 'Воскресенье')], max_length=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VerificationPhone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.TextField(blank=True, null=True)),
                ('code', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.TextField(default='')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars')),
                ('ref_code', models.TextField(blank=True, default='', null=True)),
                ('bonuses', models.IntegerField(default=0)),
                ('month_bonuses', models.IntegerField(default=0)),
                ('email', models.TextField(default='')),
                ('name', models.TextField(default='')),
                ('sex', models.TextField(default='')),
                ('friends', models.ManyToManyField(blank=True, null=True, to='api.User')),
            ],
        ),
        migrations.CreateModel(
            name='TrainTimer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(default=datetime.datetime(2021, 4, 20, 18, 51, 4, 978423))),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.company')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='Timer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(blank=True, choices=[('0', 'Понедельник'), ('1', 'Вторник'), ('2', 'Среда'), ('3', 'Четверг'), ('4', 'Пятница'), ('5', 'Суббота'), ('6', 'Воскресенье')], max_length=1, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.company')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('0', 'Понедельник'), ('1', 'Вторник'), ('2', 'Среда'), ('3', 'Четверг'), ('4', 'Пятница'), ('5', 'Суббота'), ('6', 'Воскресенье')], max_length=1)),
                ('timelines', models.ManyToManyField(blank=True, null=True, to='api.TimeLine')),
            ],
        ),
        migrations.CreateModel(
            name='FinishedTrain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minutes', models.IntegerField(default=0)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('bill', models.IntegerField(default=0)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.company')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='days',
            field=models.ManyToManyField(blank=True, null=True, to='api.Schedule'),
        ),
        migrations.AddField(
            model_name='company',
            name='images',
            field=models.ManyToManyField(blank=True, null=True, to='api.MyImage'),
        ),
        migrations.AddField(
            model_name='company',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.user'),
        ),
        migrations.AddField(
            model_name='company',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='api.ServiceCategory'),
        ),
    ]
