# Generated by Django 3.1.7 on 2021-04-21 18:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210420_1920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='count_people',
        ),
        migrations.AddField(
            model_name='timeline',
            name='limit_people',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='traintimer',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 21, 18, 54, 9, 463094)),
        ),
    ]
