# Generated by Django 3.1.7 on 2021-04-22 22:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210421_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='timer',
            name='price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='traintimer',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 22, 22, 37, 36, 408364)),
        ),
    ]
