# Generated by Django 3.1.7 on 2021-04-24 00:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210423_0405'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='card_token',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='card_type',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='last_numbers',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='traintimer',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 24, 0, 46, 26, 515918)),
        ),
    ]
