# Generated by Django 3.1.7 on 2021-04-26 21:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20210424_0046'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='second_name',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='traintimer',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 26, 21, 59, 31, 762)),
        ),
    ]
