# Generated by Django 3.1.7 on 2021-05-03 13:44

import qfit.yandex_s3_storage
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20210426_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='avatar',
            field=models.FileField(blank=True, null=True, storage=qfit.yandex_s3_storage.ClientDocsStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='myimage',
            name='image',
            field=models.FileField(blank=True, null=True, storage=qfit.yandex_s3_storage.ClientDocsStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='image',
            field=models.FileField(blank=True, null=True, storage=qfit.yandex_s3_storage.ClientDocsStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='traintimer',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 3, 13, 44, 11, 666777)),
        ),
    ]
