# Generated by Django 3.1.7 on 2021-05-12 22:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20210512_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traintimer',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 12, 22, 37, 5, 770239)),
        ),
    ]
