# Generated by Django 3.1.7 on 2021-11-05 20:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20210512_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='telegram_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='traintimer',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 5, 20, 9, 27, 115142)),
        ),
    ]
