# Generated by Django 3.1.7 on 2021-11-08 17:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20211105_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telegram_friends',
            field=models.ManyToManyField(blank=True, null=True, related_name='telegram', to='api.User'),
        ),
        migrations.AlterField(
            model_name='traintimer',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 8, 17, 27, 45, 32088)),
        ),
        migrations.AlterField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(blank=True, null=True, related_name='app_friends', to='api.User'),
        ),
    ]
